source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SmartStickyPullToRefresh_Example', :exclusive => true do
  pod 'SmartStickyPullToRefresh', :path => '../'
end

target 'SmartStickyPullToRefresh_Tests', :exclusive => true do
  pod 'SmartStickyPullToRefresh', :path => '../'

  
end
